apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-webapp
spec:
  selector:
    matchLabels:
      app: devops-webapp
  replicas: 1
  template:
    metadata:
      labels:
        app: devops-webapp
    spec:
      containers:
      - name: devops-webapp
        image: marian14/web_app
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "pg"
        - name: DB_URL
          value: "jdbc:postgresql://postgres:5432/test"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        ports:
        - containerPort: 8080

