# apiVersion: v1
# kind: PersistentVolume # Create a PV
# metadata:
#   name: postgresql-data # Sets PV's name
#   labels:
#     type: local # Sets PV's type to local
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 64Mi # Sets PV Volume
#   accessModes:
#   - ReadWriteOnce
#   hostPath:
#     path: "/data/volume"


apiVersion: v1
kind: PersistentVolume # Create a PV
metadata:
  name: mysql-data # Sets PV's name
  labels:
    type: local # Sets PV's type to local
spec:
  storageClassName: manual
  capacity:
    storage: 64Mi # Sets PV Volume
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/data/volume"
